name: darkroom
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/my-computer.png
    - assets/images/recycle-bin.png
    - assets/images/map_click.png
    - assets/images/background.png
    - assets/images/background_2.png
    - assets/images/background_4.png
    - assets/images/test.png
    - assets/audio/windows-98-startup-sound.wav
    - assets/audio/BSOD.mp3

  fonts:
    - family: MorePerfectDOSVGA
      fonts:
        - asset: fonts/MorePerfectDOSVGA.ttf